model_params:
  objective: "regression"
  metric: "rmse"
  num_leaves: 255
  max_depth: 8
  learning_rate: 0.1
  n_estimators: 1000
  feature_fraction: 0.9
  bagging_fraction: 0.8
  bagging_freq: 5
  min_child_samples: 20
  reg_lambda: 3.0
  verbose: -1
  random_state: 42

target_col: "target"
categorical_features:
  - "city_nm"